/*
 * RestFul Api ToDoList
 *
 * Open Api For ToDoList
 *
 * API version: 1.0.0
 * Contact: muhammadarifbudiman@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateOrUpdate struct {
	Name string `json:"name,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
